import { and, asc, eq, gt, inArray, isNull, ne, sql } from 'drizzle-orm';
import type { Db } from '../db/index.js';
import { discordLinks, games, users } from '../db/schema.js';
import { ApiError } from '../lib/errors.js';
import { isoNow } from '../lib/time.js';
import type { SettingsService } from './settings.js';

const DISCORD_API = 'https://discord.com/api/v10';
const DISCORD_CDN = 'https://cdn.discordapp.com';

/**
 * What the OAuth flow asks for, and why each one.
 *
 * `identify` is the account itself. `guilds` is how membership of the
 * operator's server is checked without the bot needing to be in it first.
 * `guilds.join` is what lets someone be added to that server rather than
 * merely told to go and find it.
 *
 * Deliberately absent: anything touching messages or email. A link is for
 * signing in and finding the other people here, and neither needs more.
 */
export const DISCORD_SCOPES = ['identify', 'guilds', 'guilds.join'] as const;

export interface DiscordIdentity {
  id: string;
  username: string;
  global_name?: string | null;
  avatar?: string | null;
}

/** One linked account, as the rest of the app sees it. */
export interface DiscordLinkInfo {
  discordId: string;
  username: string;
  globalName: string | null;
  avatarUrl: string | null;
  showUsername: boolean;
  inGuild: boolean;
  linkedAt: string;
}

/** Someone else here who is in the same Discord, offered as a friend suggestion. */
export interface DiscordNeighbour {
  userId: string;
  username: string;
  /** Only when they have chosen to show it. */
  discordUsername: string | null;
  avatarUrl: string | null;
}

interface TokenResponse {
  access_token: string;
  refresh_token?: string;
  expires_in?: number;
}

/**
 * Discord, as far as this server is concerned.
 *
 * Two halves that share credentials and nothing else: OAuth on behalf of a
 * player, and a bot acting as the server. They are one service because they
 * are configured together and are useless apart — the bot is what adds a
 * player to the guild after they authorise, and the guild is what the bot
 * announces into.
 *
 * A note on what is *not* here, because it is the obvious thing to expect:
 * Discord publishes no friends list to third-party applications. There is no
 * scope for it and no endpoint. "Friends from Discord" therefore means the
 * people you share the operator's server with, which is the closest thing the
 * platform actually exposes — and, since linking pushes everyone into that one
 * server, is very nearly the same set in practice.
 */
export class DiscordService {
  constructor(
    private readonly db: Db,
    private readonly settings: SettingsService,
    private readonly basePath = '',
  ) {}

  /* --------------------------------------------------------------- config */

  /** Whether linking and signing in are available at all. */
  get isConfigured(): boolean {
    const { discordClientId, discordClientSecret } = this.settings.get();
    return Boolean(discordClientId && discordClientSecret);
  }

  /** Whether the bot half — posting, adding people to the guild — can work. */
  get hasBot(): boolean {
    return Boolean(this.settings.get().discordBotToken);
  }

  /** What the client is allowed to know about the configuration. */
  status(): {
    configured: boolean;
    hasBot: boolean;
    guildId: string | null;
    inviteUrl: string | null;
    requireGuild: boolean;
  } {
    const s = this.settings.get();
    return {
      configured: this.isConfigured,
      hasBot: this.hasBot,
      guildId: s.discordGuildId,
      inviteUrl: s.discordInviteUrl,
      requireGuild: s.discordRequireGuild,
    };
  }

  /**
   * Where to send someone to authorise.
   *
   * `state` is generated by the caller and checked on the way back; without it
   * the callback would accept a code obtained anywhere, which is how an
   * attacker attaches their own Discord account to someone else's session.
   */
  authorizeUrl(state: string, redirectUri: string): string {
    const { discordClientId } = this.settings.get();
    if (!discordClientId) throw ApiError.badRequest('Discord is not configured on this server');

    const params = new URLSearchParams({
      client_id: discordClientId,
      redirect_uri: redirectUri,
      response_type: 'code',
      scope: DISCORD_SCOPES.join(' '),
      state,
      // Always re-ask: a silent re-auth would make "link a different account"
      // impossible without visiting Discord's own settings.
      prompt: 'consent',
    });
    return `${DISCORD_API}/oauth2/authorize?${params.toString()}`;
  }

  /* ----------------------------------------------------------------- http */

  private async call<T>(path: string, init: RequestInit & { auth: string }): Promise<T> {
    const { auth, ...rest } = init;
    const response = await fetch(`${DISCORD_API}${path}`, {
      ...rest,
      headers: {
        ...(rest.headers ?? {}),
        Authorization: auth,
        'Content-Type': 'application/json',
      },
    });

    if (response.status === 204) return undefined as T;

    const text = await response.text();
    if (!response.ok) {
      // Discord's own message is far more useful than a status code — it names
      // the missing permission, the bad snowflake, the unverified bot.
      throw ApiError.badRequest(
        `Discord refused ${path} (${response.status}): ${text.slice(0, 300)}`,
      );
    }
    return (text ? JSON.parse(text) : undefined) as T;
  }

  /* ---------------------------------------------------------------- oauth */

  /** Trades the callback's code for tokens. */
  async exchangeCode(code: string, redirectUri: string): Promise<TokenResponse> {
    const { discordClientId, discordClientSecret } = this.settings.get();
    if (!discordClientId || !discordClientSecret) {
      throw ApiError.badRequest('Discord is not configured on this server');
    }

    const response = await fetch(`${DISCORD_API}/oauth2/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        client_id: discordClientId,
        client_secret: discordClientSecret,
        grant_type: 'authorization_code',
        code,
        redirect_uri: redirectUri,
      }),
    });

    if (!response.ok) {
      throw ApiError.badRequest(
        `Discord would not exchange that code (${response.status}). Check the redirect URI matches the one registered on the application.`,
      );
    }
    return (await response.json()) as TokenResponse;
  }

  async identify(accessToken: string): Promise<DiscordIdentity> {
    return this.call<DiscordIdentity>('/users/@me', { auth: `Bearer ${accessToken}` });
  }

  /** Whether this access token's owner is in the operator's guild. */
  async isInGuild(accessToken: string): Promise<boolean> {
    const guildId = this.settings.get().discordGuildId;
    if (!guildId) return false;

    const guilds = await this.call<Array<{ id: string }>>('/users/@me/guilds', {
      auth: `Bearer ${accessToken}`,
    });
    return guilds.some((guild) => guild.id === guildId);
  }

  /**
   * Adds someone to the guild, using the `guilds.join` grant they gave.
   *
   * Being told "go and join the Discord" is a step people do not take. This is
   * why the scope is asked for. Returns false when it could not be done — no
   * bot, no guild configured, or the bot lacking Create Invite — so the caller
   * can fall back to showing the invite link.
   */
  async addToGuild(discordId: string, accessToken: string): Promise<boolean> {
    const { discordBotToken, discordGuildId } = this.settings.get();
    if (!discordBotToken || !discordGuildId) return false;

    try {
      await this.call(`/guilds/${discordGuildId}/members/${discordId}`, {
        method: 'PUT',
        auth: `Bot ${discordBotToken}`,
        body: JSON.stringify({ access_token: accessToken }),
      });
      return true;
    } catch {
      // A 204 means "already a member", which `call` treats as success; any
      // real failure here is a permissions problem the invite link works around.
      return false;
    }
  }

  /* ----------------------------------------------------------------- links */

  /** Records or refreshes a link. */
  link(
    userId: string,
    identity: DiscordIdentity,
    tokens: TokenResponse,
    inGuild: boolean,
  ): DiscordLinkInfo {
    const existing = this.db
      .select({ userId: discordLinks.userId })
      .from(discordLinks)
      .where(eq(discordLinks.discordId, identity.id))
      .get();

    if (existing && existing.userId !== userId) {
      throw ApiError.badRequest(
        'That Discord account is already linked to another account on this server.',
      );
    }

    const expiresAt = tokens.expires_in
      ? new Date(Date.now() + tokens.expires_in * 1000).toISOString()
      : null;

    const row = {
      userId,
      discordId: identity.id,
      username: identity.username,
      globalName: identity.global_name ?? null,
      avatar: identity.avatar ?? null,
      accessToken: tokens.access_token,
      refreshToken: tokens.refresh_token ?? null,
      tokenExpiresAt: expiresAt,
      inGuild,
      guildCheckedAt: isoNow(),
      linkedAt: isoNow(),
    };

    this.db
      .insert(discordLinks)
      .values(row)
      .onConflictDoUpdate({
        target: discordLinks.userId,
        // `showUsername` is deliberately absent: re-linking must not quietly
        // republish a handle somebody had chosen to hide.
        set: {
          discordId: row.discordId,
          username: row.username,
          globalName: row.globalName,
          avatar: row.avatar,
          accessToken: row.accessToken,
          refreshToken: row.refreshToken,
          tokenExpiresAt: row.tokenExpiresAt,
          inGuild: row.inGuild,
          guildCheckedAt: row.guildCheckedAt,
        },
      })
      .run();

    return this.forUser(userId) as DiscordLinkInfo;
  }

  unlink(userId: string): void {
    this.db.delete(discordLinks).where(eq(discordLinks.userId, userId)).run();
  }

  /** Whether the handle is shown to other players. */
  setVisibility(userId: string, showUsername: boolean): DiscordLinkInfo {
    const link = this.db.select().from(discordLinks).where(eq(discordLinks.userId, userId)).get();
    if (!link) throw ApiError.notFound('No Discord account is linked');

    this.db.update(discordLinks).set({ showUsername }).where(eq(discordLinks.userId, userId)).run();
    return this.forUser(userId) as DiscordLinkInfo;
  }

  forUser(userId: string): DiscordLinkInfo | null {
    const row = this.db.select().from(discordLinks).where(eq(discordLinks.userId, userId)).get();
    if (!row) return null;

    return {
      discordId: row.discordId,
      username: row.username,
      globalName: row.globalName,
      avatarUrl: avatarUrl(row.discordId, row.avatar),
      showUsername: row.showUsername,
      inGuild: row.inGuild,
      linkedAt: row.linkedAt,
    };
  }

  /** How many players have linked, for the admin panel's own reassurance. */
  linkedCount(): number {
    return (
      this.db
        .select({ count: sql<number>`count(*)` })
        .from(discordLinks)
        .get()?.count ?? 0
    );
  }

  /** The account a Discord id signs in as, if any. */
  userIdFor(discordId: string): string | null {
    return (
      this.db
        .select({ userId: discordLinks.userId })
        .from(discordLinks)
        .where(eq(discordLinks.discordId, discordId))
        .get()?.userId ?? null
    );
  }

  /**
   * The handle to show beside a player, or null.
   *
   * Every read of another player's Discord name goes through here, so the
   * default-off toggle cannot be forgotten at one call site.
   */
  visibleHandleFor(userId: string): string | null {
    const row = this.db
      .select({ username: discordLinks.username, show: discordLinks.showUsername })
      .from(discordLinks)
      .where(eq(discordLinks.userId, userId))
      .get();
    return row?.show ? row.username : null;
  }

  /** Handles for several players at once, honouring each one's choice. */
  visibleHandlesFor(userIds: string[]): Map<string, string> {
    if (userIds.length === 0) return new Map();
    const rows = this.db
      .select({
        userId: discordLinks.userId,
        username: discordLinks.username,
        show: discordLinks.showUsername,
      })
      .from(discordLinks)
      .where(inArray(discordLinks.userId, userIds))
      .all();
    return new Map(rows.filter((row) => row.show).map((row) => [row.userId, row.username]));
  }

  /**
   * Other players here who are also in the operator's Discord.
   *
   * The nearest thing to "your Discord friends" the platform allows: there is
   * no friends scope and no endpoint for it. Since linking pushes everyone
   * into the same server, sharing it is a real signal — these are the people
   * you are actually alongside.
   */
  neighbours(userId: string, limit = 24): DiscordNeighbour[] {
    const self = this.db
      .select({ inGuild: discordLinks.inGuild })
      .from(discordLinks)
      .where(eq(discordLinks.userId, userId))
      .get();
    if (!self?.inGuild) return [];

    return this.db
      .select({
        userId: discordLinks.userId,
        username: users.username,
        discordUsername: discordLinks.username,
        show: discordLinks.showUsername,
        discordId: discordLinks.discordId,
        avatar: discordLinks.avatar,
      })
      .from(discordLinks)
      .innerJoin(users, eq(users.id, discordLinks.userId))
      .where(and(eq(discordLinks.inGuild, true), ne(discordLinks.userId, userId)))
      .limit(limit)
      .all()
      .map((row) => ({
        userId: row.userId,
        username: row.username,
        discordUsername: row.show ? row.discordUsername : null,
        avatarUrl: row.show ? avatarUrl(row.discordId, row.avatar) : null,
      }));
  }

  /* ------------------------------------------------------------------ bot */

  /** Posts a plain message to the announcement channel. */
  async post(content: string, channelId?: string): Promise<void> {
    await this.send({ content }, channelId);
  }

  /** Posts an embed — what a game announcement looks like. */
  async postEmbed(embed: Record<string, unknown>, channelId?: string): Promise<void> {
    await this.send({ embeds: [embed] }, channelId);
  }

  private async send(payload: Record<string, unknown>, channelId?: string): Promise<void> {
    const { discordBotToken, discordChannelId } = this.settings.get();
    const target = channelId ?? discordChannelId;

    if (!discordBotToken) throw ApiError.badRequest('No Discord bot token is configured');
    if (!target) throw ApiError.badRequest('No Discord channel is configured');

    await this.call(`/channels/${target}/messages`, {
      method: 'POST',
      auth: `Bot ${discordBotToken}`,
      body: JSON.stringify(payload),
    });
  }

  /**
   * Announces games added since the last time this ran.
   *
   * A watermark rather than a flag per game: it survives restarts, and does
   * not need a column. Switching announcements on sets the watermark to now,
   * which is what stops a server with ten thousand existing games announcing
   * every one of them the moment the operator ticks the box.
   *
   * Only matched games are announced. An unmatched entry is a folder name and
   * nothing else — no cover, no blurb — and "Some.Game.REPACK-XYZ" is not
   * worth pushing to a Discord.
   *
   * Returns how many were posted. Failures are the caller's to log: a Discord
   * outage must not stop a scan or a schedule.
   */
  async announceNewGames(limit = 5): Promise<number> {
    const s = this.settings.get();
    if (!s.discordAnnounceNewGames || !this.hasBot || !s.discordChannelId) return 0;

    // Without an absolute address the embed's artwork would resolve against
    // discord.com. Posting text-only would be worse than waiting for setup.
    const publicBaseUrl = s.discordPublicUrl?.replace(/\/+$/, '') ?? null;

    // First run: start the clock rather than announcing the whole back catalog.
    if (!s.discordLastAnnouncedAt) {
      this.settings.update({ discordLastAnnouncedAt: isoNow() });
      return 0;
    }

    const fresh = this.db
      .select({
        id: games.id,
        title: games.title,
        summary: games.summary,
        addedAt: games.addedAt,
        coverImageId: games.coverImageId,
        releaseDate: games.releaseDate,
        genres: games.genres,
      })
      .from(games)
      .where(
        and(
          gt(games.addedAt, s.discordLastAnnouncedAt),
          isNull(games.missingAt),
          ne(games.matchStatus, 'unmatched'),
        ),
      )
      .orderBy(asc(games.addedAt))
      .limit(limit)
      .all();

    if (fresh.length === 0) return 0;

    let posted = 0;
    for (const game of fresh) {
      await this.postEmbed({
        title: game.title,
        description: game.summary ? truncate(game.summary, 300) : undefined,
        color: 0x2bb7f5,
        // Absolute, because Discord fetches it itself rather than through a
        // player's browser — a relative path would resolve to discord.com.
        thumbnail:
          game.coverImageId && publicBaseUrl
            ? { url: `${publicBaseUrl}${this.basePath}/api/images/${game.coverImageId}` }
            : undefined,
        fields: [
          ...(game.releaseDate
            ? [{ name: 'Released', value: game.releaseDate.slice(0, 4), inline: true }]
            : []),
          ...(game.genres && game.genres.length > 0
            ? [{ name: 'Genres', value: game.genres.slice(0, 3).join(', '), inline: true }]
            : []),
        ],
        footer: { text: 'Just added to the archive' },
      });
      posted += 1;
      // Advance per game, so a failure part way through does not re-announce
      // the ones that already went out.
      this.settings.update({ discordLastAnnouncedAt: game.addedAt });
    }

    return posted;
  }

  /** Confirms the bot token works and says who it is. */
  async botIdentity(): Promise<{ id: string; username: string }> {
    const { discordBotToken } = this.settings.get();
    if (!discordBotToken) throw ApiError.badRequest('No Discord bot token is configured');
    return this.call<{ id: string; username: string }>('/users/@me', {
      auth: `Bot ${discordBotToken}`,
    });
  }

  /** Authenticates the REST-backed bot when the server starts. */
  async startBot(): Promise<{ id: string; username: string } | null> {
    if (!this.hasBot) return null;
    return this.botIdentity();
  }
}

/** Keeps an embed description inside something a reader will actually read. */
function truncate(value: string, max: number): string {
  const collapsed = value.replace(/\s+/g, ' ').trim();
  if (collapsed.length <= max) return collapsed;
  const cut = collapsed.slice(0, max);
  const lastSpace = cut.lastIndexOf(' ');
  return `${(lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).trimEnd()}…`;
}

/** Discord's CDN path for an avatar, or null when they have never set one. */
function avatarUrl(discordId: string, avatar: string | null): string | null {
  if (!avatar) return null;
  const extension = avatar.startsWith('a_') ? 'gif' : 'png';
  return `${DISCORD_CDN}/avatars/${discordId}/${avatar}.${extension}?size=128`;
}
